"""empty message

Revision ID: 48724c37c2f8
Revises: a2973e7d5016
Create Date: 2022-03-27 19:45:02.694323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48724c37c2f8'
down_revision = 'a2973e7d5016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('opening_date', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('number_buildings', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospitals', 'number_buildings')
    op.drop_column('hospitals', 'opening_date')
    # ### end Alembic commands ###
