"""empty message

Revision ID: 8cca31de1faa
Revises: 64a7e178214c
Create Date: 2022-03-27 14:19:03.989993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cca31de1faa'
down_revision = '64a7e178214c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('specialization', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('birthday', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'birthday')
    op.drop_column('doctors', 'salary')
    op.drop_column('doctors', 'specialization')
    # ### end Alembic commands ###
